# Generated by Django 5.2.16 on 2026-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_assignment_options_assignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
