# Generated by Django 6.0.7 on 2026-07-24 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commandes", "0003_alter_order_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("QUOTE_REFUSED", "Devis refusé - Réassignation requise"),
                            ("NEW_ORDER_CREATED", "Nouvelle commande créée"),
                            ("NEW_ASSIGNMENT", "Nouvelle mission attribuée"),
                            ("QUOTE_ACCEPTED", "Devis accepté par le client"),
                            ("PRESTATAIRE_ASSIGNED", "Nouveau prestataire attribué"),
                            ("NEW_QUOTE_RECEIVED", "Nouveau devis reçu"),
                        ],
                        max_length=50,
                    ),
                ),
                ("est_lu", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="commandes.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]
