# Generated by Django 5.2.7 on 2026-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('QUOTE_REFUSED', 'Devis refusé - Réassignation requise'), ('NEW_ORDER_CREATED', 'Nouvelle commande créée'), ('REASSIGNMENT_NEEDED', 'Réassignation nécessaire'), ('NEW_ASSIGNMENT', 'Nouvelle mission attribuée'), ('QUOTE_ACCEPTED', 'Devis accepté par le client'), ('PRESTATAIRE_ASSIGNED', 'Nouveau prestataire attribué'), ('NEW_QUOTE_RECEIVED', 'Nouveau devis reçu')], max_length=50),
        ),
    ]
