# Generated by Django 5.2.7 on 2026-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_order_uuid_quote_description_quote_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREEE', 'Créée'), ('EN_TRAITEMENT', 'En traitement'), ('ASSIGNEE', 'Assignée'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('REPORTEE', 'Reportée'), ('A_REASSIGNER', 'À réassigner'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='CREEE', max_length=50),
        ),
    ]
