# Generated by Django 5.2.7 on 2026-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_category_image_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='orders/voice_notes/'),
        ),
    ]
