# Generated by Django 5.2.7 on 2026-08-26 09:23

import SimpleOQuotidien.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_order_voice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='voice_note',
            field=models.FileField(blank=True, null=True, storage=SimpleOQuotidien.storage.get_raw_media_storage, upload_to='orders/voice_notes/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=SimpleOQuotidien.storage.get_raw_media_storage, upload_to='devis_pdf/'),
        ),
    ]
