# Generated by Django 6.0.7 on 2026-07-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modification", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVOYE", "Envoyé"),
                            ("ACCEPTE", "Accepté"),
                            ("REFUSE", "Refusé"),
                        ],
                        default="ENVOYE",
                        max_length=20,
                    ),
                ),
                ("price", models.CharField(max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modification", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREEE", "Créée"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("ASSIGNEE", "Assignée"),
                            ("ACCEPTEE", "Acceptée"),
                            ("REFUSEE", "Refusée"),
                            ("REPORTEE", "Reportée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="CREEE",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("localisation", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("budget", models.FloatField()),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="orders/"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modification", models.DateTimeField(auto_now=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="commandes.category",
                    ),
                ),
            ],
        ),
    ]
