# Generated by Django 6.0.7 on 2026-07-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
