# Generated by Django 6.0.7 on 2026-07-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0003_alter_order_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["nom"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date_creation"]},
        ),
    ]
