# Generated by Django 6.0.7 on 2026-07-25 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0004_alter_category_options_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="devis_pdf/"),
        ),
    ]
