# Generated by Django 5.2.7 on 2026-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='motif_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de réponse'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée (délai dépassé)')], default='EN_ATTENTE', max_length=20),
        ),
    ]
