# Generated by Django 5.2.7 on 2026-08-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assignment_date_reponse_assignment_motif_refus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataireprofile',
            name='verification_status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=20),
        ),
    ]
