# Generated by Django 5.2.7 on 2026-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_prestataireprofile_verification_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='prestataireprofile',
            name='motif_statut',
            field=models.TextField(blank=True, help_text='Motif du rejet ou de la suspension, conservé pour traçabilité.', null=True),
        ),
    ]
