# Generated by Django 5.2.7 on 2026-08-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
