# Generated by Django 5.2.7 on 2026-08-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_order_voice_note'),
        ('users', '0006_alter_notes_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='commandes.order', unique=True),
        ),
    ]
