# Generated by Django 5.2.7 on 2026-08-26 09:23

import SimpleOQuotidien.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notes_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataireprofile',
            name='cni_passeport',
            field=models.FileField(storage=SimpleOQuotidien.storage.get_raw_media_storage, upload_to='Prestataire/cni/'),
        ),
        migrations.AlterField(
            model_name='prestataireprofile',
            name='justificatif',
            field=models.FileField(storage=SimpleOQuotidien.storage.get_raw_media_storage, upload_to='Prestataire/justificatifs/'),
        ),
    ]
