"""
Django settings for SimpleOQuotidien project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from django.templatetags.static import static
from datetime import timedelta
import os
from pathlib import Path
from urllib.parse import urlsplit

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# URL de l'application front-end (Next.js) — utilisée pour construire les liens
# envoyés par e-mail (activation, assignation, devis, notifications). L'app tourne
# en local pour l'instant, d'où le défaut localhost ; à surcharger en production
# via la variable d'environnement FRONTEND_URL.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')
_frontend_url_parts = urlsplit(FRONTEND_URL)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-rcgiq6850$gzrw_^e202j!gdc6+qgwd#v%f7t0)=8fu#&=t3m8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

AUTH_USER_MODEL = 'users.Utilisateur'

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    'cloudinary_storage',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'cloudinary',

    'users',
    'commandes',
    'rest_framework',
    'corsheaders',
    'notifications',

    'djoser',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'anymail',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.security.SecurityMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


ROOT_URLCONF = "SimpleOQuotidien.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SimpleOQuotidien.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Douala'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Le disque de Render est éphémère : tout fichier écrit dans MEDIA_ROOT (photos de
# service, CNI/justificatifs, PDF de devis, notes vocales) disparaît au prochain
# déploiement. On bascule donc sur Cloudinary dès que ses identifiants sont fournis
# (variable CLOUDINARY_URL) ; en local, sans cette variable, on retombe sur le
# stockage disque classique pour ne rien casser en dev.
# NB : depuis Django 4.2, le stockage par défaut se configure via STORAGES —
# l'ancien réglage DEFAULT_FILE_STORAGE n'est plus lu du tout par Django 5.x,
# donc le définir seul ne bascule jamais réellement les uploads vers Cloudinary.
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL')
STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if CLOUDINARY_URL else
            'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USER_ID_FIELD': 'id',
    'SEND_ACTIVATION_EMAIL': True,
    'SEND_CONFIRMATION_EMAIL': False,
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_URL': 'password-reset/{uid}/{token}',
    # Djoser 2.x lit ces 3 clés (et non 'DOMAIN'/'site_name', qui sont ignorées en
    # silence) pour construire le lien envoyé par e-mail — d'où le lien qui pointait
    # vers le backend (localhost:8000) au lieu du frontend. On les dérive de
    # FRONTEND_URL pour rester cohérent avec le reste des e-mails (devis, assignation).
    'EMAIL_FRONTEND_PROTOCOL': _frontend_url_parts.scheme,
    'EMAIL_FRONTEND_DOMAIN': _frontend_url_parts.netloc,
    'EMAIL_FRONTEND_SITE_NAME': 'SimpleOQuotidien',
    
    # 🎨 Association des templates d'e-mail personnalisés
    'EMAIL': {
        'activation': 'users.email.ActivationEmail',
        'password_reset': 'users.email.PasswordResetEmail',
    },
    
    'SERIALIZERS': {
        'user_create_password_retype': 'users.serializers.UtilisateurCreateSerializer',
        'user': 'users.serializers.UtilisateurSerializer',
        'current_user': 'users.serializers.UtilisateurSerializer',
    },
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'SimpleOQuotidien.exception_handlers.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'SimpleOQuotidien API',
    'DESCRIPTION': 'Documentation de l\'API SimpleOQuotidien',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),

    "ROTATE_REFRESH_TOKENS": True,
    'BLACKLIST_AFTER_ROTATION': True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "TOKEN_OBTAIN_SERIALIZER": "users.serializers.CustomTokenObtainPairSerializer",
}

CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
]
# Autoriser toutes les origines en dev local uniquement
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Celery / Redis
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6380/0')
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE

# Configuration Email via Brevo HTTP API (plus fiable que SMTP sur Render)
EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
ANYMAIL = {
    'BREVO_API_KEY': os.environ.get('BREVO_API_KEY', ''),
}

# L'adresse expéditeur (doit être un e-mail validé dans votre compte Brevo)
DEFAULT_FROM_EMAIL = 'SimpleOQuotidien <tsaffotagouffomegane@gmail.com>'
# PASSWORD_RESET_TIMEOUT = 3600
# 86400 secondes = 24 heures
PASSWORD_RESET_TIMEOUT = 86400

# Les valeurs DEBUG et SECRET_KEY sont déjà définies plus haut via os.environ.get()
UNFOLD = {
    "SITE_TITLE": "SimpleÔQuotidien",
    "SITE_HEADER": "SimpleÔQuotidien",
    # "SITE_SUBHEADER": "Gestion Immobilière Premium",
    "SITE_SYMBOL": "home",  # icône Material Symbols proche de ton logo maison
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SITE_ICON": lambda request: static("images/logo.png"),
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("images/logo.png"),
        },
    ],
    "LOGIN": {
        "image": lambda request: static("images/logo.png"),
    },
    "COLORS": {
        "primary": {
            "50": "236 253 250",
            "100": "204 251 241",
            "200": "153 246 228",
            "300": "94 234 212",
            "400": "45 212 191",
            "500": "0 89 79",     # ← vert sapin/teal de ton logo
            "600": "0 74 66",
            "700": "0 59 53",
            "800": "0 46 41",
            "900": "0 33 30",
            "950": "0 20 18",
        },
    },
    "STYLES": [
        lambda request: static("css/unfold-custom.css"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Utilisateurs",
                "separator": True,
                "items": [
                    {
                        "title": "Utilisateurs",
                        "icon": "person",
                        "link": "/admin/users/utilisateur/",
                    },
                    {
                        "title": "Prestataires",
                        "icon": "engineering",
                        "link": "/admin/users/prestataireprofile/",
                    },
                ],
            },
            {
                "title": "Commandes",
                "separator": True,
                "items": [
                    {
                        "title": "Commandes",
                        "icon": "shopping_cart",
                        "link": "/admin/commandes/order/",
                    },
                    {
                        "title": "Devis",
                        "icon": "receipt_long",
                        "link": "/admin/commandes/quote/",
                    },
                    {
                        "title": "Catégories",
                        "icon": "category",
                        "link": "/admin/commandes/category/",
                    },
                ],
            },
        ],
    },
}